package Entropy;

import java.io.IOException;
import java.util.StringTokenizer;

import org.apache.hadoop.io.LongWritable;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.mapreduce.Mapper;

public class EntropyMapper   extends Mapper<LongWritable, Text, Text, Text> {
	
	public void map(LongWritable key, Text value, Context context) 
			throws IOException, InterruptedException{
		// Read and tokenize text string. Assuming this is a pair file
		// generated by PairGenerator, each line is in the format: 
		// RID1 RID2 similarity 
		String line = value.toString();
		StringTokenizer tokenizer = new StringTokenizer(line);
		// Getting the record key and preparing the sorted record
		String element = tokenizer.nextToken();
		int attr_count = -1;
		while (tokenizer.hasMoreTokens()) {
			attr_count++;
			String val = tokenizer.nextToken();
			context.write(new Text(String.valueOf(attr_count)), new Text(val+" 1"));
		}
	}
}
